FICHAS=[
  {
    id:'espuma_queso',icon:'🧀',name:'Espuma de Queso (Sifón 1L)',
    category:'Salsas',allergens:'Leche',
    ingredientes:[
      {name:'Nata 35% MG',qty:'400 g'},{name:'Queso crema',qty:'200 g'},
      {name:'Queso curado rallado fino',qty:'120 g'},{name:'Leche',qty:'80 g'},
      {name:'Gelatina (hojas)',qty:'4 g (2 hojas)'},{name:'Pimienta negra',qty:'1 g'},{name:'Sal',qty:'2 g'},
    ],
    pasos:['Hidratar la gelatina en agua fría.','Calentar la nata y la leche sin que lleguen a hervir.','Añadir queso crema y queso rallado. Triturar hasta mezcla homogénea.','Incorporar la gelatina escurrida y triturar de nuevo.','Colar fino para evitar grumos.','Introducir en sifón de 1L y cargar con 2 cargas.','Reposar en frío al menos 2 horas antes de usar.'],
    conservacion:'Conservar a 4°C. Consumir en 48 horas.',rendimiento:'1 sifón ≈ 20–25 raciones de tapa.',
  },
  {
    id:'bechamel_base',icon:'🥣',name:'Base de Bechamel (Croquetas)',
    category:'Bases',allergens:'Gluten, Leche',
    ingredientes:[
      {name:'Mantequilla',qty:'1 kg'},{name:'Harina',qty:'1 kg'},
      {name:'Leche',qty:'1,5 L'},{name:'Nata',qty:'1,5 L'},
      {name:'Caldo',qty:'6 L'},{name:'Gelatina hidratada',qty:'60 g'},
    ],
    pasos:['Fundir la mantequilla en rondeau a fuego medio.','Añadir la harina y cocinar el roux 2-3 minutos removiendo.','Incorporar leche y nata calientes poco a poco sin parar de remover.','Añadir el caldo correspondiente según la variedad.','Cocinar hasta obtener bechamel cremosa que se despega de las paredes.','Añadir la gelatina hidratada y mezclar bien.','Incorporar el ingrediente principal según receta.','Extender en bandejas y enfriar en cámara.'],
    conservacion:'Envasar al vacío. Refrigerar 0–4°C.',rendimiento:'Base para todas las variedades de croqueta.',
  },
  {
    id:'cq_jamon_f',icon:'🥣',name:'Masa Croqueta de Jamón',
    category:'Croquetas',allergens:'Gluten, Leche, Huevo',
    ingredientes:[
      {name:'Base de bechamel',qty:'1 receta'},{name:'Jamón serrano loncheado',qty:'1,5 kg'},
    ],
    pasos:['Pasar el jamón serrano loncheado por la picadora de carne.','Añadir el jamón al líquido caliente (caldo, leche y nata).','Incorporar progresivamente al roux mientras se forma la bechamel.','Cocinar hasta textura cremosa.','Extender en bandejas y enfriar en cámara.'],
    conservacion:'Envasar al vacío bolsas 3.000 g. Refrigerar 0–4°C.',rendimiento:'Bolsas 3.000 g · 50 uds × 60 g por bolsa.',
  },
  {
    id:'cq_pollo_f',icon:'🥣',name:'Masa Croqueta de Pollo',
    category:'Croquetas',allergens:'Gluten, Leche, Huevo',
    ingredientes:[
      {name:'Base de bechamel',qty:'1 receta'},{name:'Pollos enteros',qty:'2 uds'},
    ],
    pasos:['Cocer los pollos enteros para obtener el caldo.','Utilizar el caldo para elaborar la base líquida de la bechamel.','Desmenuzar y picar la carne del pollo.','Incorporar la carne al final de la elaboración.','Extender la masa en bandejas y enfriar.'],
    conservacion:'Envasar al vacío bolsas 3.000 g. Refrigerar 0–4°C.',rendimiento:'Bolsas 3.000 g · 50 uds × 60 g por bolsa.',
  },
  {
    id:'cq_cocido_f',icon:'🥣',name:'Masa Croqueta de Cocido',
    category:'Croquetas',allergens:'Gluten, Leche, Huevo',
    ingredientes:[
      {name:'Base de bechamel',qty:'1 receta'},{name:'Morcillo',qty:'1 kg'},
      {name:'Tocino de cerdo',qty:'1 kg'},{name:'Cabeza de lomo',qty:'1 kg'},
      {name:'Huesos de jamón',qty:'1 kg'},{name:'Pollo',qty:'1/2 ud'},
    ],
    pasos:['Elaborar un cocido con todos los ingredientes y obtener 6 L de caldo.','Picar las carnes a cuchillo.','Usar los 6 L de caldo en la base común.','Añadir las carnes al final.','Enfriar y envasar.'],
    conservacion:'Envasar al vacío bolsas 3.000 g. Refrigerar 0–4°C.',rendimiento:'Bolsas 3.000 g · 50 uds × 60 g por bolsa.',
  },
  {
    id:'cq_setas_f',icon:'🥣',name:'Masa Croqueta Setas y Trufa',
    category:'Croquetas',allergens:'Gluten, Leche, Huevo',
    ingredientes:[
      {name:'Mantequilla',qty:'1 kg'},{name:'Harina',qty:'1 kg'},
      {name:'Leche',qty:'1,5 L'},{name:'Nata',qty:'1,5 L'},
      {name:'Caldo de pollo',qty:'4 L'},{name:'Gelatina hidratada',qty:'60 g'},
      {name:'Setas congeladas',qty:'2 bolsas'},
    ],
    pasos:['Cocinar las setas hasta que pierdan el agua.','Preparar roux con mantequilla y harina.','Incorporar leche, nata y 4 L de caldo (la seta aporta agua, se reduce 2 L respecto a base).','Cocinar la bechamel hasta textura cremosa.','Integrar las setas y la gelatina.','Extender en bandejas y enfriar.'],
    conservacion:'Envasar al vacío bolsas 2.500 g. Refrigerar 0–4°C.',rendimiento:'Bolsas 2.500 g · 50 uds × 50 g por bolsa.',
  },
  {
    id:'cq_buti_f',icon:'🥣',name:'Masa Croqueta de Butifarrón',
    category:'Croquetas',allergens:'Gluten, Leche, Huevo',
    ingredientes:[
      {name:'Base de bechamel',qty:'1 receta'},{name:'Butifarrón',qty:'2 kg'},
    ],
    pasos:['Blanquear el butifarrón.','Pasar el butifarrón por la picadora de carne.','Añadir al líquido caliente e incorporar al roux.','Cocinar, enfriar y envasar.'],
    conservacion:'Envasar al vacío bolsas 2.000 g. Refrigerar 0–4°C.',rendimiento:'Bolsas 2.000 g · 50 uds × 40 g por bolsa.',
  },
  {
    id:'patata_conf',icon:'🥔',name:'Patata Confitada para Tortilla',
    category:'Patata',allergens:'Huevo',
    ingredientes:[
      {name:'Patata agria',qty:'3.000 g'},{name:'Cebolla pochada',qty:'400 g'},
      {name:'Aceite de oliva',qty:'3.800 g'},
    ],
    pasos:['Pelar y picar la patata para tortilla.','Colocar en gastronorm grande y cubrir con 3.800 g de aceite de oliva.','Hornear a 120°C hasta confitar la patata.','Subir a 200°C para dorar ligeramente.','Retirar, colar y mezclar con 400 g de cebolla pochada.','Guardar en táper gastronorm cubierto a ras con parte del aceite de confitar.'],
    conservacion:'0–4°C. Reutilizar aceite de confitados anteriores.',rendimiento:'3.400 g de mezcla ≈ 19 pintos de tortilla.',
  },
  {
    id:'cebolla_poch',icon:'🧅',name:'Cebolla Pochada',
    category:'Bases',allergens:'',
    ingredientes:[
      {name:'Cebolla',qty:'2 kg'},{name:'Aceite de oliva',qty:'200 g'},{name:'Sal',qty:'10 g'},
    ],
    pasos:['Pelar y cortar la cebolla en juliana fina.','Calentar el aceite en rondeau o gastronorm amplia.','Añadir la cebolla y la sal.','Cocinar a fuego suave 35–45 minutos, removiendo regularmente.','Mantener el pochado sin dorar hasta obtener textura muy tierna y melosa.'],
    conservacion:'0–4°C. 4 días recomendados.',rendimiento:'2 kg cebolla cruda → 1,5 kg cebolla pochada.',
  },
  {
    id:'churros_pat',icon:'🥔',name:'Churros de Patata Estabilizados',
    category:'Patata',allergens:'Gluten, Leche, Huevo',
    ingredientes:[
      {name:'Puré de patata',qty:'2.150 g'},{name:'Copos de patata',qty:'150 g'},
      {name:'Mantequilla',qty:'150 g'},{name:'Queso curado rallado fino',qty:'270 g'},
      {name:'Huevos M',qty:'3 uds'},{name:'Harina de trigo',qty:'240 g'},
      {name:'Maicena',qty:'80 g'},{name:'Sal',qty:'25 g'},{name:'Pimienta negra',qty:'3 g'},
    ],
    pasos:['Calentar el puré de patata y añadir la mantequilla hasta fundir.','Incorporar los copos de patata y mezclar hasta hidratar completamente.','Añadir harina y maicena y trabajar la masa hasta homogeneizar.','Dejar enfriar la masa a unos 60°C.','Añadir los huevos uno a uno.','Incorporar queso rallado, sal y pimienta.','Guardar en manga o recipiente y reposar mínimo 4 horas en cámara.'],
    conservacion:'Hasta 48 horas en cámara. Freír a 170–175°C directamente desde cámara.',rendimiento:'Según peso final de masa.',
  },
  {
    id:'ensaladilla_sov',icon:'🥗',name:'Ensaladilla Soviética',
    category:'Frías',allergens:'Huevo, Pescado, Mostaza',
    ingredientes:[
      {name:'Patata agria',qty:'10 kg'},{name:'Atún en aceite',qty:'1 lata'},
      {name:'Aceituna rellena',qty:'800 g'},{name:'Zanahoria',qty:'1 kg'},
      {name:'Huevos duros',qty:'10 uds'},{name:'Mayonesa Hellmanns',qty:'1 cubo'},
      {name:'AOVE',qty:'c/s'},{name:'Sal y pimienta negra',qty:'c/s'},
    ],
    pasos:['Cocer la patata en agua con sal hasta que quede tierna.','Cocer la zanahoria y los huevos.','Trocear o desmenuzar patata, zanahoria, huevo y aceituna rellena.','Añadir el atún escurrido.','Ligar con mayonesa Hellmanns y ajustar con AOVE, sal y pimienta.'],
    conservacion:'48 horas en cámara a 0–4°C.',rendimiento:'Según demanda del día.',
  },
  {
    id:'ensaladilla_agua',icon:'🥑',name:'Ensaladilla de Aguacate',
    category:'Frías',allergens:'Huevo, Mostaza',
    ingredientes:[
      {name:'Aguacate',qty:'1 kg'},{name:'Pepinillo',qty:'20 g'},
      {name:'Alcaparras',qty:'20 g'},{name:'Huevos duros',qty:'4 uds'},
      {name:'Tabasco',qty:'8 g'},{name:'Salsa Perrins',qty:'8 g'},
      {name:'Zumo de lima',qty:'24 g'},{name:'Sal',qty:'10 g'},{name:'Mayonesa',qty:'200 g'},
    ],
    pasos:['Triturar en Thermomix pepinillo, alcaparras, huevo duro, tabasco, salsa Perrins, mayonesa y sal.','Machacar aparte el aguacate con varillas junto con el zumo de lima.','Mezclar la base triturada con el aguacate hasta obtener textura cremosa con estructura.'],
    conservacion:'24 horas en cámara a 0–4°C.',rendimiento:'25 g por unidad en Dolorosa de salmón.',
  },
  {
    id:'salsa_brava',icon:'🫙',name:'Salsa Brava',
    category:'Salsas',allergens:'',
    ingredientes:[
      {name:'Chile chipotle',qty:'200 g'},{name:'Ajo pelado',qty:'20 g'},
      {name:'Tomate frito Hida',qty:'1 lata (2.500 g)'},{name:'Vinagre de vino',qty:'125 g'},
      {name:'Pimentón dulce',qty:'15 g'},{name:'Sal',qty:'10 g'},{name:'Pimienta negra',qty:'1 g'},
    ],
    pasos:['Introducir todos los ingredientes en Thermomix.','Triturar hasta obtener salsa homogénea.','Envasar y refrigerar.'],
    conservacion:'Refrigerar 0–4°C. Vida útil 7 días.',rendimiento:'Aproximadamente 3 kg de salsa.',
  },
  {
    id:'alioli',icon:'🫙',name:'Alioli',
    category:'Salsas',allergens:'Huevo',
    ingredientes:[
      {name:'Huevo pasteurizado',qty:'400 g'},{name:'Ajo pelado',qty:'2 uds'},
      {name:'Sal',qty:'5 g'},{name:'Pimienta negra',qty:'5 g'},
      {name:'Aceite de girasol',qty:'800 ml'},{name:'Aceite de oliva suave',qty:'400 ml'},
    ],
    pasos:['Introducir huevo, ajo, sal y pimienta en vaso.','Emulsionar añadiendo el aceite en hilo fino.','Continuar hasta obtener alioli estable y cremoso.'],
    conservacion:'Refrigerar 0–4°C. Vida útil 5 días.',rendimiento:'≈ 1,6 L de alioli.',
  },
  {
    id:'fd_pollo_f',icon:'🍲',name:'Fondo Pollo Campero (Arroz)',
    category:'Fondos',allergens:'Apio',
    ingredientes:[
      {name:'Pollo campero',qty:'4 uds'},{name:'Ajo pelado',qty:'100 g'},
      {name:'Cebolla',qty:'1 kg'},{name:'Pimentón dulce',qty:'25 g'},
      {name:'Verdura para paella',qty:'1 bolsa (2,5 kg)'},{name:'Alcachofas',qty:'1 kg'},
      {name:'Tomate Hida',qty:'1 lata'},{name:'Sal y pimienta',qty:'c/s'},
    ],
    pasos:['Deshuesar los 4 pollos camperos y reservar los huesos para el caldo.','Cortar la carne en trozos pequeños de bocado.','Sofreír ajo y cebolla; añadir la verdura para paella y la alcachofa.','Incorporar el pollo troceado y cocinar.','Añadir tomate y pimentón; salpimentar.','Mojar con caldo de los huesos y cocinar hasta obtener fondo concentrado.','Pasar a gastronorm, enfriar completamente y envasar al vacío en porciones de 350 g.'],
    conservacion:'Envasado al vacío, 0–4°C.',rendimiento:'≈ 30 bolsas de 350 g. 1 bolsa por ración de arroz campero.',
  },
  {
    id:'fd_sepia_f',icon:'🍲',name:'Fondo de Sepia (Arroces)',
    category:'Fondos',allergens:'Moluscos',
    ingredientes:[
      {name:'Sepia troceada',qty:'1 caja'},{name:'Ajo pelado',qty:'100 g'},
      {name:'Cebolla',qty:'1 kg'},{name:'Pimiento rojo',qty:'1 kg'},
      {name:'Tomate Hida',qty:'1 lata'},{name:'Pimentón de la Vera',qty:'50 g'},
    ],
    pasos:['Sofreír ajo, cebolla y pimiento rojo.','Añadir la sepia troceada y rehogar.','Incorporar tomate y pimentón.','Cocinar hasta obtener fondo concentrado de sepia.','Pasar a gastronorm, enfriar y envasar al vacío en bolsas de 200 g.'],
    conservacion:'Envasado al vacío, 0–4°C.',rendimiento:'Bolsas 200 g. 1 bolsa por ración arroz señoret o negro.',
  },
  {
    id:'bacalao_pilpil',icon:'🐟',name:'Bacalao Confitado + Pil Pil',
    category:'Pescado',allergens:'Pescado',
    ingredientes:[
      {name:'Lomo bacalao jumbo congelado',qty:'según demanda'},
      {name:'Aceite de oliva',qty:'c/s'},{name:'Ajo',qty:'c/s'},{name:'Guindilla',qty:'c/s'},
    ],
    pasos:['Descongelar lentamente en cámara 0–4°C durante 24 horas.','Secar ligeramente el bacalao.','Confitar cubierto de aceite de oliva con ajo y guindilla a 70–80°C.','Retirar el bacalao en lascas.','Emulsionar el aceite de confitado con la gelatina del bacalao hasta obtener pil pil ligado y brillante.'],
    conservacion:'0–4°C. Usar en 48 horas.',rendimiento:'100 g de lascas + pil pil por pintxo.',
  },
  {
    id:'albond_f',icon:'🥩',name:'Albóndigas de Ternera',
    category:'Carnes',allergens:'Gluten, Huevo, Leche',
    ingredientes:[
      {name:'Carne picada de ternera',qty:'2 kg'},{name:'Ajo',qty:'50 g'},
      {name:'Cebolla pochada',qty:'400 g'},{name:'Nata',qty:'200 g'},
      {name:'Orégano fresco',qty:'1 manojo'},{name:'Huevos',qty:'6 uds'},
      {name:'Pan brioche',qty:'2 uds'},{name:'Sal',qty:'55 g'},{name:'Pimienta negra',qty:'5 g'},
    ],
    pasos:['Picar fino ajo y orégano.','Mezclar todos los ingredientes hasta obtener masa homogénea.','Formar bolas de 70 g.','Hornear a 260°C durante 5 minutos para sellar y fijar la forma.','Envasar al vacío: 4 uds + 250 g demi glace por bolsa.'],
    conservacion:'Envasado al vacío, 0–4°C.',rendimiento:'Bolsas: 4 albóndigas + 250 g demi glace.',
  },
  {
    id:'tortilla_f',icon:'🍳',name:'Pinto de Tortilla',
    category:'Tortilla',allergens:'Huevo',
    ingredientes:[
      {name:'Mezcla patata + cebolla',qty:'175 g'},{name:'Huevos M',qty:'3 uds'},
      {name:'Yema líquida pasteurizada',qty:'≈ 1 yema'},{name:'Sal',qty:'pizca'},
      {name:'Aceite de oliva',qty:'c/s'},
    ],
    pasos:['Escurrir ligeramente la mezcla de patata confitada.','Batir 3 huevos, la yema pasteurizada y una pizca de sal.','Mezclar con 175 g de patata.','Calentar sartén con poco aceite de oliva.','Cuajar la tortilla jugosa, emplatar y enviar inmediatamente a sala.'],
    conservacion:'Servir al momento.',rendimiento:'3.000 g patata + 400 g cebolla = 3.400 g mezcla ≈ 19 pintos.',
  },
  {
    id:'arroz_campero',icon:'🍚',name:'Arroz Pollo Campero',
    category:'Arroces',allergens:'Apio',
    ingredientes:[
      {name:'Fondo pollo campero',qty:'1 bolsa (350 g)'},{name:'Arroz',qty:'120 g'},
      {name:'Aceite de oliva',qty:'c/s'},{name:'Caldo de ave',qty:'750 ml (5 cucharones)'},
      {name:'Demi glace de pollo',qty:'c/s'},{name:'Cebollino picado',qty:'c/s'},
    ],
    pasos:['Calentar paellera con aceite de oliva.','Añadir una bolsa de fondo de pollo campero.','Incorporar 120 g de arroz y nacararlo.','Añadir 750 ml de caldo de ave.','Cocer 5 minutos a fuego fuerte y luego al mínimo hasta consumir el caldo.','Fuera del fuego, terminar con hilos de demi glace de pollo y cebollino picado.'],
    conservacion:'Servir al momento.',rendimiento:'1 ración.',
  },
  {
    id:'arroz_senyor',icon:'🍚',name:'Arroz del Senyoret',
    category:'Arroces',allergens:'Moluscos, Crustáceos',
    ingredientes:[
      {name:'Fondo de sepia',qty:'1 bolsa (200 g)'},{name:'Arroz',qty:'120 g'},
      {name:'Aceite de oliva',qty:'c/s'},{name:'Caldo de pescado',qty:'750 ml'},
      {name:'Gambas langostineras',qty:'4 colas'},{name:'Aceite de ajo y perejil',qty:'c/s'},
    ],
    pasos:['Calentar paellera con aceite de oliva.','Añadir una bolsa de fondo de sepia.','Nacarar 120 g de arroz.','Mojar con 750 ml de caldo de pescado.','Cocer 5 min fuerte y luego al mínimo.','En el pase, saltear 4 colas de gamba al ajillo y colocarlas sobre el arroz.','Terminar con aceite de ajo y perejil.'],
    conservacion:'Servir al momento.',rendimiento:'1 ración.',
  },
  {
    id:'arroz_negro',icon:'🍚',name:'Arroz Negro de Sepia',
    category:'Arroces',allergens:'Moluscos',
    ingredientes:[
      {name:'Fondo de sepia',qty:'1 bolsa (200 g)'},{name:'Arroz',qty:'120 g'},
      {name:'Caldo de pescado',qty:'750 ml'},{name:'Tinta de calamar',qty:'1 punta'},
      {name:'Chipirones',qty:'60 g aprox.'},{name:'Aceite de oliva',qty:'c/s'},
      {name:'Emulsión pimiento del piquillo',qty:'c/s'},
    ],
    pasos:['Calentar paellera con aceite y añadir una bolsa de fondo de sepia.','Nacarar el arroz e incorporar una punta de tinta de calamar.','Mojar con 750 ml de caldo de pescado.','Cocer 5 min fuerte y luego al mínimo.','En el pase, saltear los chipirones y colocarlos sobre el arroz.','Terminar con emulsión de pimiento del piquillo.'],
    conservacion:'Servir al momento.',rendimiento:'1 ración.',
  },
  {
    id:'tarta_queso_f',icon:'🍮',name:'Tarta de Queso',
    category:'Postres',allergens:'Leche, Huevo',
    ingredientes:[
      {name:'Huevos',qty:'15 uds'},{name:'Crema de queso',qty:'3 kg'},
      {name:'Azúcar',qty:'900 g'},{name:'Nata',qty:'1,5 L'},
    ],
    pasos:['Mezclar crema de queso y azúcar en montadora.','Añadir huevos uno a uno.','Incorporar la nata y mezclar hasta homogeneizar.','Verter en cacerolas individuales hasta 3/4 de capacidad.','Cocer en horno mixto a 100°C y 100% vapor durante 25 minutos.','Enfriar y guardar en cámara.'],
    conservacion:'Refrigerar 0–4°C. Vida útil 4 días.',rendimiento:'Según tamaño de cacerolas individuales.',
  },
  {
    id:'tiramisu_f',icon:'🍮',name:'Tiramisú (Tazas)',
    category:'Postres',allergens:'Gluten, Huevo, Leche, Sulfitos',
    ingredientes:[
      {name:'Queso mascarpone',qty:'c/s'},{name:'Huevos',qty:'c/s'},
      {name:'Azúcar',qty:'c/s'},{name:'Café solo',qty:'c/s'},
      {name:'Amaretto',qty:'c/s'},{name:'Savoiardi',qty:'2 uds por taza'},
    ],
    pasos:['Montar huevos con azúcar.','Mezclar con queso mascarpone hasta obtener crema aireada.','Mojar 2 savoiardi en mezcla de café, azúcar y amaretto.','Colocarlos en el fondo de una taza.','Cubrir con crema de mascarpone.','Tapar cada taza con film y guardar en cámara.'],
    conservacion:'Cámara 0–4°C. Vida útil 48 horas.',rendimiento:'Por taza individual.',
  },
  {
    id:'torrija_f',icon:'🍮',name:'Torrija de Coca de Patata',
    category:'Postres',allergens:'Gluten, Leche, Huevo, Frutos secos',
    ingredientes:[
      {name:'Coca de patata perforada',qty:'1 ud'},{name:'Leche',qty:'c/s'},
      {name:'Azúcar',qty:'c/s'},{name:'Piel de naranja',qty:'c/s'},
      {name:'Piel de limón',qty:'c/s'},{name:'Mantequilla',qty:'c/s'},
      {name:'Crema de almendra (manga)',qty:'c/s'},{name:'Helado leche merengada',qty:'1 bola'},
    ],
    pasos:['Preparar infusión de leche, azúcar, piel de naranja y piel de limón.','Bañar la coca en el preparado y escurrir ligeramente.','Pasar por sartén con mantequilla y azúcar hasta dorar por ambas caras.','Guardar en táper para servicio.','Calentar 20 segundos en microondas.','Cubrir con crema de almendra, espolvorear azúcar y quemar con soplete.','Acompañar con una bola de helado de leche merengada.'],
    conservacion:'Táper en cámara. Regenerar al momento de servicio.',rendimiento:'Por ración individual.',
  },

  {
    id:'espuma_queso', icon:'🧀', name:'Espuma de Queso (Sifón 1L)',
    category:'Salsas', allergens:'Leche',
    pdf:'ficha_tecnica_espuma_de_queso.pdf',
    ingredientes:[
      {name:'Nata 35% MG',qty:'400 g'},
      {name:'Queso crema',qty:'200 g'},
      {name:'Queso curado rallado fino',qty:'120 g'},
      {name:'Leche',qty:'80 g'},
      {name:'Gelatina (hojas)',qty:'4 g (2 hojas)'},
      {name:'Pimienta negra',qty:'1 g'},
      {name:'Sal',qty:'2 g'},
    ],
    pasos:[
      'Hidratar la gelatina en agua fría.',
      'Calentar la nata y la leche sin que lleguen a hervir.',
      'Añadir queso crema y queso rallado. Triturar hasta mezcla homogénea.',
      'Incorporar la gelatina escurrida y triturar de nuevo.',
      'Colar fino para evitar grumos.',
      'Introducir en sifón de 1L y cargar con 2 cargas.',
      'Reposar en frío al menos 2 horas antes de usar.',
    ],
    conservacion:'Conservar a 4°C. Consumir en 48 horas.',
    rendimiento:'1 sifón ≈ 20–25 raciones de tapa.',
  },
  {
    id:'cq_jamon_f', icon:'🥣', name:'Masa Croqueta de Jamón',
    category:'Croquetas', allergens:'Gluten, Leche, Huevo',
    pdf:'Fichas_Tecnicas_Croquetas_La_Dolores_Completo.pdf',
    ingredientes:[
      {name:'Mantequilla',qty:'1 kg'},
      {name:'Harina',qty:'1 kg'},
      {name:'Leche',qty:'1,5 L'},
      {name:'Nata',qty:'1,5 L'},
      {name:'Caldo',qty:'6 L'},
      {name:'Gelatina hidratada',qty:'60 g'},
      {name:'Jamón serrano loncheado',qty:'1,5 kg'},
    ],
    pasos:[
      'Pasar el jamón por la picadora de carne.',
      'Fundir mantequilla, añadir harina y cocinar el roux.',
      'Incorporar leche y nata calientes.',
      'Añadir jamón al líquido caliente e incorporar al roux.',
      'Añadir el caldo y cocinar hasta textura cremosa.',
      'Añadir gelatina hidratada.',
      'Extender en bandejas y enfriar en cámara.',
    ],
    conservacion:'Envasar al vacío en bolsas de 3.000 g. Refrigerar 0–4°C.',
    rendimiento:'Bolsas 3.000 g · 50 uds × 60 g por bolsa.',
  },
  {
    id:'cq_setas_f', icon:'🥣', name:'Masa Croqueta Setas y Trufa',
    category:'Croquetas', allergens:'Gluten, Leche, Huevo',
    pdf:'Fichas_Tecnicas_Croquetas_La_Dolores_Completo.pdf',
    ingredientes:[
      {name:'Mantequilla',qty:'1 kg'},
      {name:'Harina',qty:'1 kg'},
      {name:'Leche',qty:'1,5 L'},
      {name:'Nata',qty:'1,5 L'},
      {name:'Caldo de pollo',qty:'4 L'},
      {name:'Gelatina hidratada',qty:'60 g'},
      {name:'Setas congeladas',qty:'2 bolsas'},
    ],
    pasos:[
      'Cocinar las setas hasta que pierdan el agua.',
      'Preparar roux con mantequilla y harina.',
      'Incorporar leche, nata y 4 L de caldo (la seta aporta agua, se reduce 2 L).',
      'Cocinar la bechamel hasta textura cremosa.',
      'Integrar las setas y la gelatina.',
      'Extender en bandejas y enfriar.',
    ],
    conservacion:'Envasar al vacío en bolsas de 2.500 g.',
    rendimiento:'50 uds × 50 g por bolsa.',
  },
  {
    id:'albond_f', icon:'🥩', name:'Albóndigas de Ternera',
    category:'Carnes', allergens:'Gluten, Huevo, Leche',
    ingredientes:[
      {name:'Carne picada de ternera',qty:'2 kg'},
      {name:'Ajo',qty:'50 g'},
      {name:'Cebolla pochada',qty:'400 g'},
      {name:'Nata',qty:'200 g'},
      {name:'Orégano fresco',qty:'1 manojo'},
      {name:'Huevos',qty:'6 uds'},
      {name:'Pan brioche',qty:'2 uds'},
      {name:'Sal',qty:'55 g'},
      {name:'Pimienta negra',qty:'5 g'},
    ],
    pasos:[
      'Picar fino ajo y orégano.',
      'Mezclar todos los ingredientes hasta masa homogénea.',
      'Formar bolas de 70 g.',
      'Hornear a 260°C durante 5 minutos para sellar.',
      'Envasar al vacío: 4 uds + 250 g demi glace por bolsa.',
    ],
    conservacion:'Envasado al vacío, 0–4°C.',
    rendimiento:'Bolsas: 4 albóndigas + 250 g demi glace.',
  },
  {
    id:'brava_f', icon:'🫙', name:'Salsa Brava',
    category:'Salsas', allergens:'',
    ingredientes:[
      {name:'Chile chipotle',qty:'200 g'},
      {name:'Ajo pelado',qty:'20 g'},
      {name:'Tomate frito Hida',qty:'1 lata (2.500 g)'},
      {name:'Vinagre de vino',qty:'125 g'},
      {name:'Pimentón dulce',qty:'15 g'},
      {name:'Sal',qty:'10 g'},
      {name:'Pimienta negra',qty:'1 g'},
    ],
    pasos:[
      'Triturar todos los ingredientes en Thermomix.',
      'Triturar hasta obtener salsa homogénea.',
      'Envasar y refrigerar.',
    ],
    conservacion:'Refrigerar 0–4°C. Vida útil 7 días.',
    rendimiento:'Aproximadamente 3 kg de salsa.',
  },
  {
    id:'alioli_f', icon:'🫙', name:'Alioli',
    category:'Salsas', allergens:'Huevo',
    ingredientes:[
      {name:'Huevo pasteurizado',qty:'400 g'},
      {name:'Ajo pelado',qty:'2 uds'},
      {name:'Sal',qty:'5 g'},
      {name:'Pimienta negra',qty:'5 g'},
      {name:'Aceite de girasol',qty:'800 ml'},
      {name:'Aceite de oliva suave',qty:'400 ml'},
    ],
    pasos:[
      'Introducir huevo, ajo, sal y pimienta en vaso.',
      'Emulsionar añadiendo el aceite en hilo fino.',
      'Continuar hasta obtener alioli estable y cremoso.',
    ],
    conservacion:'Refrigerar 0–4°C. Vida útil 5 días.',
    rendimiento:'≈ 1,6 L de alioli.',
  },
  {
    id:'tarta_queso_f', icon:'🍮', name:'Tarta de Queso',
    category:'Postres', allergens:'Leche, Huevo',
    ingredientes:[
      {name:'Huevos',qty:'15 uds'},
      {name:'Crema de queso',qty:'3 kg'},
      {name:'Azúcar',qty:'900 g'},
      {name:'Nata',qty:'1,5 L'},
    ],
    pasos:[
      'Mezclar crema de queso y azúcar en montadora.',
      'Añadir huevos uno a uno.',
      'Incorporar la nata y mezclar hasta homogeneizar.',
      'Verter en cacerolas individuales hasta ¾ de capacidad.',
      'Cocer en horno mixto a 100°C y 100% vapor durante 25 minutos.',
      'Enfriar y guardar en cámara.',
    ],
    conservacion:'Refrigerar 0–4°C. Vida útil 4 días.',
    rendimiento:'Según tamaño de cacerolas.',
  },
];
